### ISSUE TITLE
ManiFest Needs to be Out of Src and Be Not in a folder

### ISSUE THREAD

**Issue by trafort** [zicsus/makerlog-extension#1]
Hi Zicsus,

I've Built some Chrome Extesitons Before, On @IamTregsthedev, and The Manifest has to be in  a Place where Chrome can Read it. It Expects in to be Still. I've Sumbited a PR, that will Fix this!

Proof:

![](https://i.gyazo.com/cb1ab9adba9c91f41a87526c78d717be.png)

**Comment by trafort** [comment]
I have Summbited the PR, I'm Wondering Maybe Your Future Plans for this Extestion, Should be A New  tab page. maybe another Extestion. Testing to see if the Pr Works!

** Edit:

**Comment by radioblahaj** [comment]
I also found some other errors in your code 
Best to ingore them as you are.bot done
The background folder is missing my dude

**Comment by zicsus** [comment]
Can you be more specific? 
What errors?
